version: '3.8'

services:
  webapi:
    build:
      context: ./src/SocialMedia
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel_network

volumes:
  db_data:
    driver: local

networks:
  laravel_network:
    driver: bridge


